matrix:
  include:
    - language: node_js
      node_js:
        - "8"
      os:
        - linux
        - osx
before_install:
  - sudo apt-get update
  - sudo apt install libudev-dev
  - sudo apt install libusb-1.0-0-dev
before_script:
  - npm install  
  - git submodule update --remote
  - npm run make-protobuf-files
  # Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - npm run lint
  - npm test
notifications:
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

